title: invent-project-template
hero_image: images/banner.png
description: invent-project-template description
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test
    completion: engaged
  - title: Share
    completion: internal
  - title: Reflection
    completion: external
  - title: Upgrade your project
  - title: What next?
